apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "s3-resource-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "s3-resource-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "s3-resource-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
