{{- if .Values.operator.secret.create -}}
{{- if not .Values.operator.secret.data.S3_ENDPOINT_URL }}
{{- fail "operator.secret.data.S3_ENDPOINT_URL must be provided when operator.secret.create is true" }}
{{- end }}
{{- if not .Values.operator.secret.data.S3_ACCESS_KEY }}
{{- fail "operator.secret.data.S3_ACCESS_KEY must be provided when operator.secret.create is true" }}
{{- end }}
{{- if not .Values.operator.secret.data.S3_SECRET_KEY }}
{{- fail "operator.secret.data.S3_SECRET_KEY must be provided when operator.secret.create is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-resource-operator.secretName" . }}
  labels:
    {{- include "s3-resource-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.operator.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
