{{- if .Values.operator.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-resource-operator.secretName" . }}
  labels:
    {{- include "s3-resource-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.operator.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
